# Generated by Django 2.1.5 on 2021-08-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='typeAuto',
            field=models.IntegerField(default=0),
        ),
    ]
