# Generated by Django 2.1.5 on 2021-08-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20210806_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='typeAuto',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=256),
        ),
    ]
